-- Inserir produtos estáticos no banco de dados
INSERT INTO products (name, description, price, image_url, category, stock, discount_percentage, is_active) VALUES
-- Smartphones & Tablets
('iPhone 15 Pro Max 256GB', 'iPhone 15 Pro Max com 256GB de armazenamento, tela Super Retina XDR de 6.7" e sistema de câmera Pro avançado', 8999.90, '/src/assets/smartphone.jpg', 'smartphones', 50, 10, true),
('iPad Pro 12.9" 512GB', 'iPad Pro com tela Liquid Retina XDR de 12.9", chip M2 e 512GB de armazenamento', 9999.90, '/src/assets/tablet.jpg', 'smartphones', 30, 17, true),
('AirPods Pro 3ª Geração', 'AirPods Pro com cancelamento ativo de ruído, áudio espacial e resistência à água', 1899.90, '/src/assets/earbuds.jpg', 'smartphones', 100, 17, true),
('iPhone 14 Pro 128GB', 'iPhone 14 Pro com tela Super Retina XDR de 6.1", sistema de câmera Pro e chip A16 Bionic', 6999.90, '/src/assets/smartphone.jpg', 'smartphones', 45, 13, true),
('Galaxy S24 Ultra 512GB', 'Samsung Galaxy S24 Ultra com S Pen integrada, câmera de 200MP e 512GB de armazenamento', 7499.90, '/src/assets/smartphone.jpg', 'smartphones', 35, 0, true),
('iPad Air 5ª Geração 256GB', 'iPad Air com chip M1, tela Liquid Retina de 10.9" e 256GB de armazenamento', 4999.90, '/src/assets/tablet.jpg', 'smartphones', 40, 14, true),
('AirPods Max Silver', 'AirPods Max com cancelamento ativo de ruído, áudio espacial personalizado e design premium', 3999.90, '/src/assets/earbuds.jpg', 'smartphones', 25, 0, true),
('iPhone 13 Pro 256GB', 'iPhone 13 Pro com sistema de câmera Pro, tela ProMotion e chip A15 Bionic', 5999.90, '/src/assets/smartphone.jpg', 'smartphones', 60, 14, true),
('Galaxy Tab S9 Ultra', 'Samsung Galaxy Tab S9 Ultra com tela de 14.6", S Pen incluída e performance excepcional', 8999.90, '/src/assets/tablet.jpg', 'smartphones', 20, 0, true),
('iPhone SE 3ª Geração 128GB', 'iPhone SE com chip A15 Bionic, Touch ID e design clássico em corpo compacto', 2999.90, '/src/assets/smartphone.jpg', 'smartphones', 75, 14, true),
('Galaxy Buds 2 Pro', 'Galaxy Buds2 Pro com cancelamento ativo de ruído inteligente e som de alta qualidade', 899.90, '/src/assets/earbuds.jpg', 'smartphones', 80, 25, true),
('iPad Mini 6ª Geração 256GB', 'iPad Mini com chip A15 Bionic, tela Liquid Retina de 8.3" e suporte ao Apple Pencil', 4299.90, '/src/assets/tablet.jpg', 'smartphones', 55, 0, true),
('Pixel 8 Pro 256GB', 'Google Pixel 8 Pro com câmera avançada com IA, tela de 6.7" e 256GB de armazenamento', 6499.90, '/src/assets/smartphone.jpg', 'smartphones', 30, 11, true),

-- Gaming
('Mouse Gamer RGB 16000 DPI', 'Mouse gamer de alta precisão com sensor óptico de 16000 DPI e iluminação RGB customizável', 199.90, '/src/assets/gaming-mouse.jpg', 'gaming', 150, 0, true),
('Webcam 4K para Streaming', 'Webcam 4K com autofoco, correção de luz automática e microfone integrado para streaming profissional', 649.90, '/src/assets/webcam.jpg', 'gaming', 85, 0, true),
('Cadeira Gamer RGB Pro', 'Cadeira gamer ergonômica com iluminação RGB, apoio lombar ajustável e material premium', 1599.90, '/src/assets/gaming-chair.jpg', 'gaming', 40, 20, true),
('Headset Gamer RGB 7.1', 'Headset gamer com som surround 7.1, microfone removível e iluminação RGB sincronizável', 299.90, '/src/assets/gaming-headset.jpg', 'gaming', 120, 0, true),
('Teclado Mecânico RGB', 'Teclado mecânico com switches Cherry MX, iluminação RGB por tecla e design anti-ghosting', 549.90, '/src/assets/gaming-keyboard.jpg', 'gaming', 95, 0, true),
('Monitor Gamer 27" 144Hz', 'Monitor gamer de 27" com taxa de atualização de 144Hz, tempo de resposta de 1ms e HDR', 1799.90, '/src/assets/gaming-monitor.jpg', 'gaming', 65, 18, true),
('Mouse Pad Gamer XXL RGB', 'Mouse pad gamer extra grande com iluminação RGB nas bordas e superfície otimizada para gaming', 149.90, '/src/assets/mousepad-gamer-rgb.jpg', 'gaming', 200, 25, true),
('Controle Xbox Series X Wireless', 'Controle wireless Xbox Series com tecnologia de impulso, gatilhos adaptativos e compartilhamento de áudio', 449.90, '/src/assets/controle-xbox-series.jpg', 'gaming', 110, 0, true),
('Microfone Condensador Streaming', 'Microfone condensador USB com cancelamento de ruído, pop filter e braço articulado', 399.90, '/src/assets/microfone-streaming.jpg', 'gaming', 75, 27, true),
('Kit Iluminação RGB Smart', 'Kit de iluminação RGB inteligente com controle por app, sincronização musical e 16 milhões de cores', 299.90, '/src/assets/kit-rgb-smart.jpg', 'gaming', 90, 0, true),
('Monitor Curvo 32" 165Hz', 'Monitor gamer curvo de 32" com 165Hz, curvatura 1800R e tecnologia FreeSync Premium', 2499.90, '/src/assets/gaming-monitor.jpg', 'gaming', 35, 17, true),
('Teclado 60% Mecânico Hot-Swap', 'Teclado mecânico compacto 60% com switches hot-swappable e software de customização avançado', 699.90, '/src/assets/gaming-keyboard.jpg', 'gaming', 60, 0, true),
('Headset Wireless Gaming Pro', 'Headset wireless premium com cancelamento ativo de ruído, bateria de 30h e som Hi-Fi', 799.90, '/src/assets/gaming-headset.jpg', 'gaming', 45, 20, true),
('Cadeira Gamer Ergonômica', 'Cadeira gamer premium com espuma memory foam, apoio de cabeça ajustável e base de alumínio', 2199.90, '/src/assets/gaming-chair.jpg', 'gaming', 25, 0, true),
('Joystick PlayStation 5', 'Controle DualSense PS5 com feedback tátil, gatilhos adaptativos e microfone integrado', 349.90, '/src/assets/joystick-ps5.jpg', 'gaming', 130, 13, true),
('Ring Light 18" para Stream', 'Ring light profissional de 18" com controle de temperatura de cor e suporte para smartphone', 249.90, '/src/assets/ring-light-stream.jpg', 'gaming', 70, 0, true),

-- Computadores
('Notebook Gamer RTX 4070', 'Notebook gamer com RTX 4070, processador Intel i7, 16GB RAM e SSD de 1TB para gaming extremo', 7899.90, '/src/assets/gaming-laptop.jpg', 'computadores', 30, 0, true),
('MacBook Pro 14" M3 Pro', 'MacBook Pro com chip M3 Pro, tela Liquid Retina XDR de 14" e performance profissional', 12999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 20, 13, true),
('Notebook Dell XPS 13 Plus', 'Ultrabook Dell XPS 13 Plus com tela InfinityEdge, processador Intel i7 e design premium', 8999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 25, 0, true),
('PC Gamer RTX 4080 Ryzen 7', 'PC Gamer completo com RTX 4080, Ryzen 7, 32GB RAM e RGB customizável para máxima performance', 15999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 15, 11, true),
('MacBook Air M2 13" 512GB', 'MacBook Air com chip M2, design ultrafino, bateria de longa duração e 512GB de armazenamento', 9999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 35, 0, true),
('Notebook ASUS ROG Strix', 'Notebook gamer ASUS ROG Strix com RTX 4060, tela 144Hz e sistema de resfriamento avançado', 6999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 40, 13, true),
('Mini PC Intel NUC i7', 'Mini PC compacto Intel NUC com processador i7, ideal para escritório e entretenimento', 3999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 50, 0, true),
('All-in-One iMac 24" M3', 'iMac 24" com chip M3, tela Retina 4.5K e design colorido all-in-one elegante', 13999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 18, 10, true),
('Workstation Dell Precision', 'Workstation profissional Dell Precision com Xeon, Quadro RTX e certificações ISV', 18999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 12, 0, true),
('Notebook Acer Predator Helios', 'Notebook gamer Acer Predator Helios com RTX 4070, tela 165Hz e teclado RGB mecânico', 8499.90, '/src/assets/gaming-laptop.jpg', 'computadores', 28, 15, true),
('Surface Laptop Studio 2', 'Microsoft Surface Laptop Studio 2 com tela touchscreen flexível e RTX 4050 para criatividade', 11999.90, '/src/assets/gaming-laptop.jpg', 'computadores', 22, 0, true),

-- Componentes
('Placa de Vídeo RTX 4080', 'NVIDIA GeForce RTX 4080 com 16GB GDDR6X, ray tracing de 3ª geração e DLSS 3', 6299.90, '/src/assets/graphics-card.jpg', 'componentes', 45, 13, true),
('SSD NVMe 1TB Gen4', 'SSD NVMe PCIe 4.0 de 1TB com velocidades de leitura até 7000 MB/s e garantia de 5 anos', 899.90, '/src/assets/ssd.jpg', 'componentes', 120, 0, true),
('Placa Mãe Gaming B550', 'Placa mãe AMD B550 com suporte a Ryzen 5000, WiFi 6, RGB e múltiplas conexões', 1299.90, '/src/assets/motherboard.jpg', 'componentes', 80, 19, true),
('Memória RAM 32GB DDR4', 'Kit de memória RAM 32GB (2x16GB) DDR4-3200 com dissipadores de calor e RGB', 999.90, '/src/assets/ram.jpg', 'componentes', 90, 0, true),
('Fonte 750W 80+ Gold', 'Fonte de alimentação modular 750W com certificação 80+ Gold e proteções avançadas', 699.90, '/src/assets/psu.jpg', 'componentes', 70, 0, true),
('Placa de Vídeo RTX 4090', 'NVIDIA GeForce RTX 4090 com 24GB GDDR6X, a placa de vídeo mais poderosa para gaming 4K', 12999.90, '/src/assets/graphics-card.jpg', 'componentes', 25, 13, true),
('Processador Ryzen 9 7950X', 'AMD Ryzen 9 7950X com 16 núcleos, 32 threads e arquitetura Zen 4 para máxima performance', 3999.90, '/src/assets/processador-amd.jpg', 'componentes', 35, 0, true),
('SSD NVMe 2TB Gen4', 'SSD NVMe PCIe 4.0 de 2TB com velocidades extremas e tecnologia de cache inteligente', 1699.90, '/src/assets/ssd.jpg', 'componentes', 60, 15, true),
('Memória RAM 64GB DDR5', 'Kit de memória RAM 64GB (2x32GB) DDR5-5600 com baixa latência e suporte XMP 3.0', 2999.90, '/src/assets/ram.jpg', 'componentes', 40, 0, true),
('Placa Mãe X670E ROG', 'Placa mãe premium AMD X670E com WiFi 6E, Bluetooth 5.2 e suporte a DDR5/PCIe 5.0', 2799.90, '/src/assets/motherboard.jpg', 'componentes', 30, 15, true),
('Fonte 1000W 80+ Platinum', 'Fonte modular 1000W com certificação 80+ Platinum, cabos sleeved e garantia de 10 anos', 1299.90, '/src/assets/psu.jpg', 'componentes', 50, 0, true),
('Water Cooler 360mm RGB', 'Water cooler AIO 360mm com radiador triplo, bomba silenciosa e iluminação RGB', 899.90, '/src/assets/water-cooler.jpg', 'componentes', 65, 25, true),
('Processador Intel i9-14900K', 'Intel Core i9-14900K com 24 núcleos, 32 threads e boost até 6.0GHz para performance extrema', 4299.90, '/src/assets/processador-intel.jpg', 'componentes', 28, 0, true),
('SSD SATA 4TB Pro', 'SSD SATA de 4TB para armazenamento em massa com reliability profissional e garantia estendida', 2199.90, '/src/assets/ssd.jpg', 'componentes', 40, 15, true),
('Kit Memória 128GB DDR5', 'Kit de memória RAM 128GB (4x32GB) DDR5-5200 para workstations e servidores profissionais', 8999.90, '/src/assets/ram.jpg', 'componentes', 15, 0, true),
('Processador Intel i7-13700K', 'Intel Core i7-13700K com 16 núcleos, 24 threads e performance híbrida para gaming e produtividade', 2899.90, '/src/assets/processador-intel.jpg', 'componentes', 55, 12, true),
('Processador Intel i5-13600K', 'Intel Core i5-13600K com 14 núcleos, 20 threads, ideal para gaming competitivo e multitarefas', 1899.90, '/src/assets/processador-intel.jpg', 'componentes', 75, 0, true),
('Processador Intel i9-13900KS', 'Intel Core i9-13900KS Special Edition com boost até 6.0GHz e performance líder de mercado', 5299.90, '/src/assets/processador-intel.jpg', 'componentes', 20, 12, true),
('Processador AMD Ryzen 7 7700X', 'AMD Ryzen 7 7700X com 8 núcleos, 16 threads e arquitetura Zen 4 para gaming e criação de conteúdo', 2399.90, '/src/assets/processador-amd.jpg', 'componentes', 65, 0, true),
('Processador AMD Ryzen 5 7600X', 'AMD Ryzen 5 7600X com 6 núcleos, 12 threads, excelente custo-benefício para gaming', 1599.90, '/src/assets/processador-amd.jpg', 'componentes', 85, 16, true),
('Processador AMD Ryzen 9 7900X', 'AMD Ryzen 9 7900X com 12 núcleos, 24 threads e performance excepcional para workstations', 3299.90, '/src/assets/processador-amd.jpg', 'componentes', 45, 0, true);